// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/header-utility-ia/InsightsAssistant.tsx": () => import("../components/mockups/header-utility-ia/InsightsAssistant.tsx"),
  "./components/mockups/header-utility-ia/NavigationSupportCentre.tsx": () => import("../components/mockups/header-utility-ia/NavigationSupportCentre.tsx"),
  "./components/mockups/header-utility-ia/OperationsCommand.tsx": () => import("../components/mockups/header-utility-ia/OperationsCommand.tsx"),
  "./components/mockups/header-utility-ia/SupportDock.tsx": () => import("../components/mockups/header-utility-ia/SupportDock.tsx"),
  "./components/mockups/header-utility-ia/TopbarRelocation.tsx": () => import("../components/mockups/header-utility-ia/TopbarRelocation.tsx"),
  "./components/mockups/header-utility-ia/UnifiedSupportHub.tsx": () => import("../components/mockups/header-utility-ia/UnifiedSupportHub.tsx"),
  "./components/mockups/help-control-exploration/Concierge.tsx": () => import("../components/mockups/help-control-exploration/Concierge.tsx"),
  "./components/mockups/help-control-exploration/ContextualAssist.tsx": () => import("../components/mockups/help-control-exploration/ContextualAssist.tsx"),
  "./components/mockups/help-control-exploration/Current.tsx": () => import("../components/mockups/help-control-exploration/Current.tsx"),
  "./components/mockups/help-control-exploration/ServiceHub.tsx": () => import("../components/mockups/help-control-exploration/ServiceHub.tsx"),
  "./components/mockups/help-control-exploration/SignalBeacon.tsx": () => import("../components/mockups/help-control-exploration/SignalBeacon.tsx"),
  "./components/mockups/help-control-exploration/SupportPill.tsx": () => import("../components/mockups/help-control-exploration/SupportPill.tsx"),
  "./components/mockups/mega-menu/CardGrid.tsx": () => import("../components/mockups/mega-menu/CardGrid.tsx"),
  "./components/mockups/mega-menu/CommandPalette.tsx": () => import("../components/mockups/mega-menu/CommandPalette.tsx"),
  "./components/mockups/mega-menu/IconTiles.tsx": () => import("../components/mockups/mega-menu/IconTiles.tsx"),
  "./components/mockups/mega-menu/SidebarRail.tsx": () => import("../components/mockups/mega-menu/SidebarRail.tsx"),
  "./components/mockups/mega-menu/TabbedPanel.tsx": () => import("../components/mockups/mega-menu/TabbedPanel.tsx"),
  "./components/mockups/support-cluster/Current.tsx": () => import("../components/mockups/support-cluster/Current.tsx"),
  "./components/mockups/support-cluster/FramedSupportGroup.tsx": () => import("../components/mockups/support-cluster/FramedSupportGroup.tsx")
};
