import React, { useState } from "react";
import { ArrowRight, ChevronDown, FileCheck2, FileText, Grid2X2, Landmark, LockKeyhole, Sparkles } from "lucide-react";

const GROUPS = [
  { id:"quick", label:"Quick Access", cue:"The essentials, close at hand.", icon:Grid2X2, items:[["Home","Return to your dashboard overview."],["Accounts Information","View balances and transaction history."],["Administration","Manage users, roles, and settings."],["Marketplace","Discover new banking products and services."]] },
  { id:"payments", label:"Payments & Transfers", cue:"Move money with confidence.", icon:Landmark, items:[["Account Transfer","Move funds between your Northstar accounts."],["ACH Payments","Process bulk domestic payments electronically."],["Electronic Funds Transfer (EFT)","Send funds securely to domestic vendors."],["EFT Client Returns","Manage returned and rejected EFT transactions."],["File Transfer Facility (FTF)","Batch process high-volume payment files."],["Interac e-Transfer","Send money instantly via email or text in Canada.","CA"],["Wire Payment","Execute same-day domestic or international wires."],["Zelle","Fast, safe, and easy way to send money in the US.","US"]] },
  { id:"cheques", label:"Cheques", cue:"A clearer paper trail.", icon:FileCheck2, items:[["Northstar DepositEdge","Scan and deposit cheques remotely from your office."],["Digital Cheque Service (DCS)","Manage outsourced cheque printing and mailing."],["Recon Management","Automate cheque reconciliation and reduce fraud.","US"],["Stop Payments","Place, manage, or cancel stop payment requests."],["Cheque Imaging","View and download copies of cleared cheques."]] },
  { id:"reports", label:"Reports", cue:"Understand what your team needs to know.", icon:FileText, items:[["Account transfer reports","Detailed logs of internal account movements."],["Wire Payment reports","Comprehensive history of incoming and outgoing wires."],["Electronic Report Delivery (ERD)","Secure distribution of periodic bank statements."],["File Transfer Facility (FTF) reports","Audit trails for your batch file processing."],["Recon Management reports","Discrepancy analysis for your cheque accounts."],["ACH reports","Transaction summaries for ACH batches."],["Stop payments reports","Status tracking for all stop requests."],["Digital Cheque Services reports","Analytics on outsourced cheque issuance."]] }
];

export function ProgressiveServiceReveal() {
  const [open, setOpen] = useState<string | null>(null);
  const [selected, setSelected] = useState("");
  const active = GROUPS.find(g => g.id === open);
  return <main className="min-h-[100dvh] bg-[#f6f8fb] font-['Plus_Jakarta_Sans'] text-[#14233d]">
    <header className="mx-auto flex h-[78px] max-w-[1120px] items-center justify-between px-7"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#0757b7] text-white"><Landmark size={18}/></div><span className="text-lg font-bold tracking-[-.04em]">Northstar</span></div><div className="flex items-center gap-5 text-xs font-semibold text-[#7187a1]"><span className="hidden sm:inline">Business banking workspace</span><div className="grid h-8 w-8 place-items-center rounded-full bg-[#e4edf7] text-[10px] font-bold text-[#37608d]">NS</div></div></header>
    <section className="mx-auto max-w-[1120px] px-7 pb-12 pt-14"><div className="max-w-[630px]"><div className="mb-5 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.2em] text-[#6b8cb4]"><Sparkles size={14}/> A clear place to begin</div><h1 className="text-[42px] font-bold leading-[1.08] tracking-[-.06em] text-[#102442]">Start with what<br/><span className="text-[#1467bd]">matters today.</span></h1><p className="mt-5 max-w-[520px] text-[15px] leading-7 text-[#6c819d]">Northstar keeps your workspace quiet until you choose a direction. Select a service area to reveal the tools inside.</p></div>
      <div className="mt-14 grid gap-3 md:grid-cols-2">{GROUPS.map((group) => { const Icon = group.icon; const isOpen = group.id === open; return <div key={group.id} className={`rounded-[20px] border transition-all duration-300 ${isOpen ? "border-[#a9c9eb] bg-white shadow-[0_14px_35px_rgba(33,81,132,.1)]" : "border-[#dfe7f0] bg-[#fbfcfe] hover:-translate-y-0.5 hover:border-[#b7cde5]"}`}><button aria-expanded={isOpen} onClick={() => setOpen(isOpen ? null : group.id)} className="flex w-full items-center gap-4 p-5 text-left"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${isOpen ? "bg-[#e6f1fd] text-[#0757b7]" : "bg-[#edf3f9] text-[#6d88a6]"}`}><Icon size={20}/></span><span className="flex-1"><span className="block text-[15px] font-bold">{group.label}</span><span className="mt-1 block text-xs text-[#8294aa]">{group.cue}</span></span><span className={`grid h-8 w-8 place-items-center rounded-full transition ${isOpen ? "bg-[#0757b7] text-white" : "bg-[#f0f4f8] text-[#8da0b5]"}`}>{isOpen ? <ChevronDown size={16}/> : <ArrowRight size={16}/>}</span></button>{isOpen && <div className="border-t border-[#e7eef5] px-5 pb-5 pt-3"><div className="grid gap-1 sm:grid-cols-2">{group.items.map(item => <button key={item[0]} onClick={() => setSelected(item[0])} aria-pressed={selected === item[0]} className={`group flex items-center gap-3 rounded-xl px-3 py-3 text-left transition hover:bg-[#f1f6fc] ${selected === item[0] ? "bg-[#eef6ff]" : ""}`}><span className="h-1.5 w-1.5 rounded-full bg-[#79a9d7] transition group-hover:bg-[#0757b7]"/><span className="min-w-0 flex-1"><span className="block text-xs font-bold text-[#234464] group-hover:text-[#0757b7]">{item[0]} {item[2] && <span className="ml-1 rounded bg-[#edf3f9] px-1 py-0.5 text-[9px] text-[#66809e]">{item[2]}</span>}</span><span className="mt-1 block truncate text-[10px] text-[#8a9bb0]">{item[1]}</span></span><ArrowRight size={13} className="text-[#a5b8cc] opacity-0 transition group-hover:opacity-100"/></button>)}</div></div>}</div>})}</div>
      <div className="mt-8 flex items-center gap-3 rounded-2xl border border-[#dce7f2] bg-[#edf5fd] px-5 py-4 text-xs text-[#65809e]"><LockKeyhole size={16} className="text-[#3775b3]"/><span>Your workspace is private by design. No account information is shown until you choose a service.</span></div>
    </section>
  </main>;
}