import React, { useState } from "react";
import { Check, ChevronDown, ChevronRight, FileCheck, FileText, Grid2X2, Landmark, LockKeyhole } from "lucide-react";

export type Domain = "quick" | "payments" | "cheques" | "reports";
type Service = { name: string; description: string; badge?: string };
export const domains: { id: Domain; label: string; cue: string; icon: React.ElementType; items: Service[] }[] = [
  { id:"quick", label:"Quick Access", cue:"The essentials, close at hand.", icon:Grid2X2, items:[{name:"Home",description:"Return to your dashboard overview."},{name:"Accounts Information",description:"View balances and transaction history."},{name:"Administration",description:"Manage users, roles, and settings."},{name:"Marketplace",description:"Discover new banking products and services."}] },
  { id:"payments", label:"Payments & Transfers", cue:"Move money with confidence.", icon:Landmark, items:[{name:"Account Transfer",description:"Move funds between your Northstar accounts."},{name:"ACH Payments",description:"Process bulk domestic payments electronically."},{name:"Electronic Funds Transfer (EFT)",description:"Send funds securely to domestic vendors."},{name:"EFT Client Returns",description:"Manage returned and rejected EFT transactions."},{name:"File Transfer Facility (FTF)",description:"Batch process high-volume payment files."},{name:"Interac e-Transfer",badge:"CA",description:"Send money instantly via email or text in Canada."},{name:"Wire Payment",description:"Execute same-day domestic or international wires."},{name:"Zelle",badge:"US",description:"Fast, safe, and easy way to send money in the US."}] },
  { id:"cheques", label:"Cheques", cue:"A clearer paper trail.", icon:FileCheck, items:[{name:"Northstar DepositEdge",description:"Scan and deposit cheques remotely from your office."},{name:"Digital Cheque Service (DCS)",description:"Manage outsourced cheque printing and mailing."},{name:"Recon Management",badge:"US",description:"Automate cheque reconciliation and reduce fraud."},{name:"Stop Payments",description:"Place, manage, or cancel stop payment requests."},{name:"Cheque Imaging",description:"View and download copies of cleared cheques."}] },
  { id:"reports", label:"Reports", cue:"Understand what your team needs to know.", icon:FileText, items:[{name:"Account transfer reports",description:"Detailed logs of internal account movements."},{name:"Wire Payment reports",description:"Comprehensive history of incoming and outgoing wires."},{name:"Electronic Report Delivery (ERD)",description:"Secure distribution of periodic bank statements."},{name:"File Transfer Facility (FTF) reports",description:"Audit trails for your batch file processing."},{name:"Recon Management reports",description:"Discrepancy analysis for your cheque accounts."},{name:"ACH reports",description:"Transaction summaries for ACH batches."},{name:"Stop payments reports",description:"Status tracking for all stop requests."},{name:"Digital Cheque Services reports",description:"Analytics on outsourced cheque issuance."}] }
];
export const Primary = "rounded-md bg-[#145aa3] px-4 py-2.5 text-[11px] font-bold text-white shadow-[0_3px_8px_rgba(20,90,163,.16)] hover:bg-[#0f4d8e] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#287cc8]";
export const Secondary = "rounded-md border border-[#c8d8e5] bg-white px-4 py-2.5 text-[11px] font-bold text-[#456984] hover:bg-[#f5f9fc] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#287cc8]";

function Rail({ active, onChange, setup }: {active:Domain; onChange?: (d:Domain)=>void; setup?:boolean}) {
 return <aside className="w-[255px] shrink-0 border-r border-[#d8e3ec] bg-[#eef3f8] px-4 py-5">
   <p className="mb-3 px-2 text-[9px] font-bold uppercase tracking-[.16em] text-[#7a91a6]">Service discovery</p>
   <nav aria-label="Service domains" className="space-y-1">{domains.map(d=>{const Icon=d.icon; const is=d.id===active; return <button key={d.id} onClick={()=>onChange?.(d.id)} aria-current={is?"page":undefined} className={`flex w-full items-center gap-3 rounded-md px-3 py-3 text-left transition ${is?"bg-white text-[#145aa3] shadow-sm":"text-[#506e88] hover:bg-[#e3edf5]"}`}><Icon size={16}/><span className="flex-1 text-[11px] font-bold">{d.label}</span>{is&&<ChevronRight size={14}/>}</button>})}</nav>
   {setup && <div className="mt-8 border-t border-[#d9e4ec] pt-5"><p className="px-2 text-[9px] font-bold uppercase tracking-[.16em] text-[#7a91a6]">Workspace setup</p><div className="mt-3 rounded-md border border-[#bdd5e9] bg-[#f8fbfe] px-3 py-3"><p className="text-[11px] font-bold text-[#245577]">Quick Access path</p><p className="mt-1 text-[10px] leading-4 text-[#6d869c]">Your choices stay separate from service discovery.</p></div></div>}
 </aside>
}
export function Shell({children, active="quick", setup=false, stage=0}:{children:React.ReactNode;active?:Domain;setup?:boolean;stage?:number}) {
 const [domain,setDomain]=useState<Domain>(active);
 return <main className="min-h-[800px] bg-[#f5f8fb] font-['Plus_Jakarta_Sans'] text-[#173451]">
  <header className="flex h-14 items-center justify-between border-b border-[#d7e2eb] bg-[#fbfdff] px-7"><div className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-md bg-[#145aa3] text-white"><Landmark size={15}/></span><span className="text-[18px] font-bold tracking-[-.04em]">Northstar</span><span className="border-l border-[#d7e2eb] pl-3 text-[11px] font-semibold text-[#728aa0]">Business banking workspace</span></div><div className="flex items-center gap-4 text-[11px] font-semibold text-[#5d7b95]"><button type="button">Help</button><span className="grid h-7 w-7 place-items-center rounded-full bg-[#dce9f3] text-[10px] font-bold text-[#145aa3]">NS</span></div></header>
  <div className="flex min-h-[746px]"><Rail active={domain} onChange={setDomain} setup={setup}/><section className="min-w-0 flex-1 px-9 py-6"><div className="mb-5 flex items-center gap-2 text-[10px] font-semibold text-[#668099]"><span>Service discovery</span><ChevronRight size={12}/><span>Quick Access</span>{setup&&<><ChevronRight size={12}/><span className="text-[#145aa3]">Workspace setup</span></>}</div>{setup&&<Tracker stage={stage}/>} {children}</section></div>
 </main>
}
export function Tracker({stage}:{stage:number}) { const steps=["Business profile","Connect accounts","Team & approvals","Review & activate"]; return <ol className="mb-6 flex items-center border-b border-[#dce6ee] pb-5" aria-label="Workspace setup progress">{steps.map((step,i)=><li className="flex items-center" key={step}><span className={`grid h-6 w-6 place-items-center rounded-full text-[10px] font-bold ${i<stage?"bg-[#dfefe8] text-[#247050]":i===stage?"bg-[#145aa3] text-white":"border border-[#cddbe6] bg-white text-[#718aa0]"}`}>{i<stage?<Check size={13}/>:i+1}</span><span className={`ml-2 text-[10px] font-bold ${i===stage?"text-[#145aa3]":"text-[#718aa0]"}`}>{step}</span>{i<3&&<span className={`mx-3 h-px w-10 ${i<stage?"bg-[#8abda5]":"bg-[#d4e0e9]"}`}/>}</li>)}</ol> }
export function SetupHeader({eyebrow,title,copy,step}:{eyebrow:string;title:string;copy:string;step:string}) {return <div className="mb-5 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#2c72ad]">{eyebrow}</p><h1 className="mt-1.5 text-[26px] font-bold tracking-[-.045em] text-[#183b59]">{title}</h1><p className="mt-2 max-w-[690px] text-[12px] leading-5 text-[#6a8399]">{copy}</p></div><span className="text-[10px] font-bold uppercase tracking-[.1em] text-[#7891a5]">{step}</span></div>}
export function ServiceList({domain, setupEntry=false}:{domain:Domain;setupEntry?:boolean}) { const group=domains.find(d=>d.id===domain)!; return <div className="grid gap-2 md:grid-cols-2">{setupEntry&&<button className="col-span-2 flex items-center justify-between rounded-md border border-[#8eb9dc] bg-[#edf6fd] p-4 text-left hover:bg-[#e5f1fb] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#287cc8]"><span><span className="block text-[12px] font-bold text-[#145aa3]">Set up your workspace</span><span className="mt-1 block text-[10px] text-[#5c7d98]">A first-time path for your business profile, accounts, and team controls.</span></span><ChevronRight size={17} className="text-[#145aa3]"/></button>}{group.items.map(s=><button key={s.name} className="rounded-md border border-[#dce6ee] bg-white p-3 text-left hover:border-[#abc9e1] hover:bg-[#f9fcfe] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#287cc8]"><span className="text-[11px] font-bold text-[#315774]">{s.name}{s.badge&&<span className="ml-2 rounded border border-[#c9d9e6] bg-[#f4f8fb] px-1 py-0.5 text-[8px] text-[#617d95]">{s.badge}</span>}</span><span className="mt-1 block text-[10px] leading-4 text-[#7890a4]">{s.description}</span></button>)}</div>}
export function SecurityNote(){return <div className="flex items-start gap-3 rounded-md border border-[#cfe0ed] bg-[#f0f7fc] px-4 py-3 text-[10px] leading-5 text-[#52738e]"><LockKeyhole size={15} className="mt-0.5 shrink-0 text-[#2169ac]"/><span><b className="text-[#315b7d]">Protected setup.</b> No account information is shown or changed while you make these choices.</span></div>}