import React, { useState } from "react";
import { ArrowRight, Check, Compass, LockKeyhole } from "lucide-react";
import { AppShell, Primary, StageHeader, steps } from "./_shared";

export function SetupDetected() {
 const [started, setStarted] = useState(false);
 return <AppShell stage={0}><StageHeader eyebrow="Welcome to Northstar" title="Your workspace is ready to be shaped." copy="Before Home begins showing your business information, take a few minutes to tell us how your team works." step="Step 1 of 5"/>
 <div className="grid grid-cols-[1.25fr_.75fr] gap-5"><section className="rounded-lg border border-[#d6e2eb] bg-white p-6 shadow-[0_8px_20px_rgba(34,71,105,.05)]"><h2 className="text-[17px] font-bold text-[#244663]">Five clear steps</h2><p className="mt-1 text-[11px] text-[#71899d]">You can pause anytime. We will keep your place.</p><ol className="mt-5 divide-y divide-[#e3ebf1]">{steps.map((item,i)=><li key={item} className="flex items-center gap-4 py-3"><span className={`grid h-6 w-6 place-items-center rounded-full text-[10px] font-bold ${i===0?"bg-[#145aa3] text-white":"bg-[#edf4f9] text-[#6990ae]"}`}>{i+1}</span><span className="text-[12px] font-semibold text-[#315774]">{item}</span>{i===0&&<span className="ml-auto text-[10px] font-bold text-[#2872b5]">Start here</span>}</li>)}</ol><button onClick={()=>setStarted(true)} className={`mt-6 inline-flex items-center gap-2 ${Primary}`}>{started ? "Setup saved — continue" : "Continue setup"}<ArrowRight size={14}/></button>{started&&<p className="mt-3 text-[11px] text-[#2d749f]">Your setup workspace is active.</p>}</section>
 <aside className="rounded-lg border border-[#d2e0eb] bg-[#eaf3fa] p-6"><Compass size={20} className="text-[#1f69ae]"/><h2 className="mt-5 text-[16px] font-bold text-[#244663]">Explore as you go</h2><p className="mt-2 text-[12px] leading-5 text-[#638097]">You can open the complete navigation now. Services stay available while setup is in progress.</p><ul className="mt-5 space-y-3 text-[11px] font-semibold text-[#41637e]"><li className="flex gap-2"><Check size={14} className="text-[#2872b5]"/>Browse available services</li><li className="flex gap-2"><LockKeyhole size={14} className="text-[#2872b5]"/>Review security information</li></ul></aside></div></AppShell>;
}